object Version {
    const val auto_value = "1.7"
    const val kotlin_version = "1.3.50"
    const val daggerVersion = "2.20"
    const val archCompomentVersion = "2.0.0"
    const val powermockVersion = "2.0.0-beta.5"
    const val assertjVersion = "3.14.0"
    const val assertjAndroidVersion = "1.1.1"
    const val robolectricVersion = "4.3"
    const val robolectricShadowsVersion = "3.3.2"
    const val mockKVersion = "1.8.5"
    const val navigational_component = "2.2.0-rc02"
    const val chuck = "1.1.0"
    const val appComponent = "1.1.0"
    const val room = "2.2.1"
    const val rxAndroid = "2.1.1"
    const val rxJava = "2.2.17"
    const val rxTwistedEquations = "2.0.0"
    const val rxTwistedEquationsSaveState = "2.0.1"
    const val rxBinding = "2.1.1"
    const val rxRelay = "2.0.0"
    const val retrofitConverterGson = "2.7.2"
    const val retrofit2Rxjava2Adapter = "1.0.0"
    const val androidX = "1.0.0"
    const val androidConstraintlayout = "1.1.3"
    const val multidex = "2.0.1"
    const val coreKtx = "1.2.0"
    const val espresso = "3.2.0"
    const val testRunner = "1.2.0"
    const val testRules = "1.2.0"
    const val junit = "1.1.1"
    const val picasso = "2.71828"
    const val dexter = "6.0.1"
    const val play = "1.7.1"
    const val javax_annotation = "1.0"
    const val material = "1.1.0"

    const val truth = "0.44"
    const val mockito_inline = "3.2.4"
    const val mockito_kotlin = "2.2.0"
    const val annotations = "1.1.0"
    const val test_runner = "1.2.0"

}
